# Usamos la imagen base de NanoMQ (disponible en Docker Hub)
FROM emqx/nanomq:latest

# Si necesitas una configuración personalizada, puedes copiarla aquí
# COPY ./nanomq.conf /etc/nanomq/nanomq.conf

# Exponer el puerto en el que NanoMQ escuchará
EXPOSE 1883  
# Puerto MQTT por defecto
EXPOSE 8080  
# Puerto para la interfaz web (si es necesario)
